### ISSUE TITLE
MacOS version will not run

### ISSUE THREAD

**Issue by IanAber** [geraldoramos/nikola#20] opened 2019-06-11 01:12 UTC
I downloaded the Mac OSX version and copied it to my Applications folder. On double clicking it does nothing. I can see the app in Activity Viewer but get no visible user interface. Activity monitor shows the app and two helper processes.

OSX 10.14.5

Nikola.app 0.2.6 - June 9th 227.7MB

**Comment by iaflyer** [comment] 2019-06-11 01:18
I have the same issue - downloaded 0.2.6 today, dragged it to the Applications folder. It ran but like the previous commenter, no interface. Activity monitor shows the same processes. 

I'm on OSX 10.14.5 on an iMac, 16gb memory, only other stuff running is two browsers (Firefox and Safari)

![Screen Shot 2019-06-10 at 9 18 22 PM](https://user-images.githubusercontent.com/51685482/59236684-5147f800-8bc5-11e9-85e7-07a709e66f98.png)

**Comment by Hamilt0n** [comment] 2019-06-11 02:40
I installed the app.  I signed in with Tesla account.  I can see the car icon in the toolbar but when I click on it nothing appears or happens.  Running Mac OS 10.14.5

**Comment by geraldoramos** [comment] 2019-06-11 02:46
Looks like the fact that the app does not open the main window right away might be confusing for some people. I will make it open so this usability issue will be fixed.

@Hamilt0n Regarding your issue, it seems like a different problem. I will investigate that. Did you try to restart the app and same behavior persisted? I'm on 10.14.4, will try to update and see if it is related to the version.

**Comment by IanAber** [comment] 2019-06-11 03:09
Perhaps a one time popup to tell you about the startup behaviour would help new users. Check a box to suppress the message next time would keep it clean.

**Comment by geraldoramos** [comment] 2019-06-11 05:54
New version (0.2.7) now opens the main window on startup.

Will further investigate @Hamilt0n issue, but I can't reproduce it (also running Mac OS 10.14.5).

@Hamilt0n, please open a separate issue if you are still having problems. Make sure to download the new version `0.2.7` (restart app to trigger auto-update).

**Closed by geraldoramos** 2019-06-11 05:54 UTC

**Comment by TopView** [comment] 2019-06-11 14:12
Ok, if I run `./Nikola-0.2.7-x86_64.AppImage --no-sandbox` now it starts.  I'll try to read more about this sandbox thing...
